version: '3'
services:
  django:
    container_name: django
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/src:/code
    ports:
      - 127.0.0.1:8080:8000
  node:
    container_name: node
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/:/code
    ports:
      - 127.0.0.1:80:3000
